# Generated by Django 4.2 on 2026-05-22 19:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("noivo", "Noivo(a)"),
                            ("convidado", "Convidado"),
                            ("admin", "Admin"),
                        ],
                        default="noivo",
                        max_length=20,
                    ),
                ),
                ("is_email_confirmed", models.BooleanField(default=False)),
                (
                    "email_confirmation_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "email_confirmation_expiry",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "reset_password_token",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("reset_password_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "wedding_partner_role",
                    models.CharField(
                        blank=True,
                        choices=[("noivo", "Noivo(a)"), ("noiva", "Noiva")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_2fa_enabled", models.BooleanField(default=False)),
                ("otp_secret", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="ChecklistTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Média"),
                            ("low", "Baixa"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em Andamento"),
                            ("done", "Concluído"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("is_template", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "days_before_event",
                    models.IntegerField(
                        blank=True,
                        help_text="Dias antes do evento para agrupar no frontend",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notas adicionais para a tarefa"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("photo_public_id", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("alergias", models.CharField(blank=True, max_length=255, null=True)),
                ("acompanhantes", models.PositiveIntegerField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status_presenca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pendente"),
                            ("Confirmed", "Confirmado"),
                            ("Refused", "Recusado"),
                        ],
                        default="Pending",
                        help_text="Status de presença do convidado",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("source_file", models.CharField(max_length=200)),
                ("exam", models.CharField(default="", max_length=50)),
                ("subject_area", models.JSONField()),
                ("difficulty", models.CharField(max_length=20)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "embedding_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={"db_table": "question_references",},
        ),
        migrations.CreateModel(
            name="SupplierCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="pt", max_length=10)),
                ("theme", models.CharField(default="light", max_length=20)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="UserWeddingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome_noivo", models.CharField(blank=True, max_length=100)),
                ("telefone_noivo", models.CharField(blank=True, max_length=20)),
                ("descricao_noivo", models.TextField(blank=True)),
                ("facebook_noivo", models.CharField(blank=True, max_length=255)),
                ("instagram_noivo", models.CharField(blank=True, max_length=255)),
                ("email_noivo", models.EmailField(blank=True, max_length=254)),
                ("nome_noiva", models.CharField(blank=True, max_length=100)),
                ("telefone_noiva", models.CharField(blank=True, max_length=20)),
                ("descricao_noiva", models.TextField(blank=True)),
                ("facebook_noiva", models.CharField(blank=True, max_length=255)),
                ("instagram_noiva", models.CharField(blank=True, max_length=255)),
                ("email_noiva", models.EmailField(blank=True, max_length=254)),
                ("data_casamento", models.DateField(blank=True, null=True)),
                ("hora_casamento", models.TimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=50)),
                ("cep", models.CharField(blank=True, max_length=20)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("cor_principal", models.CharField(blank=True, max_length=50)),
                ("frase_casal", models.CharField(blank=True, max_length=255)),
                ("fotos_amigos", models.JSONField(blank=True, default=list)),
                ("fotos_familia", models.JSONField(blank=True, default=list)),
                ("fotos_diversas", models.JSONField(blank=True, default=list)),
                ("historia", models.TextField(blank=True)),
                ("padrinhos", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WeddingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("id_cloudinary", models.CharField(max_length=255)),
                ("folder", models.CharField(blank=True, max_length=100)),
                ("in_use", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeddingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicado"),
                            ("inactive", "Inativo"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("url_slug", models.SlugField(max_length=64, unique=True)),
                ("template", models.CharField(default="classico", max_length=50)),
                ("groom_name", models.CharField(blank=True, max_length=100)),
                ("bride_name", models.CharField(blank=True, max_length=100)),
                ("wedding_date", models.DateField(blank=True, null=True)),
                ("wedding_time", models.TimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255)),
                ("about_us", models.TextField(blank=True)),
                ("rsvp_text", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postalcode", models.CharField(blank=True, max_length=20)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("palette", models.CharField(blank=True, max_length=50)),
                ("font", models.CharField(blank=True, max_length=50)),
                ("countdown", models.BooleanField(default=True)),
                ("map", models.BooleanField(default=True)),
                ("social", models.BooleanField(default=True)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("rsvp_count", models.PositiveIntegerField(default=0)),
                ("rsvp_conversion", models.FloatField(default=0.0)),
                ("last_visitor", models.CharField(blank=True, max_length=100)),
                ("last_visitor_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cover_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_for_sites",
                        to="app.weddingimage",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        blank=True,
                        related_name="gallery_for_sites",
                        to="app.weddingimage",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_site",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WeddingSiteHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Criação"),
                            ("edit", "Edição"),
                            ("publish", "Publicação"),
                            ("unpublish", "Despublicação"),
                            ("delete", "Exclusão"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("snapshot", models.JSONField()),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="app.weddingsite",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="WeddingIdentityShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "wedding_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_identity_share_token",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WeddingIdentityInspiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("query", models.CharField(blank=True, max_length=255)),
                ("selected_style", models.CharField(blank=True, max_length=50)),
                ("dress_code", models.CharField(blank=True, max_length=50)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "wedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspirations",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={"ordering": ["-is_favorite", "-is_liked", "-created_at"],},
        ),
        migrations.CreateModel(
            name="WeddingIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_style", models.CharField(blank=True, max_length=50)),
                ("wedding_size", models.CharField(blank=True, max_length=50)),
                ("dress_code", models.CharField(blank=True, max_length=50)),
                ("palette", models.JSONField(blank=True, default=list)),
                (
                    "wedding_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_identity",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "active_question_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("active_question_data", models.JSONField(blank=True, null=True)),
                ("questions_history", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=160)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("instagram", models.CharField(blank=True, max_length=120)),
                ("website", models.URLField(blank=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=60)),
                ("cover_image_url", models.URLField(blank=True)),
                ("cover_image_public_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "Aprovado"), ("PENDING", "Pendente")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("GLOBAL", "Global"), ("SOLO", "Solo")],
                        default="GLOBAL",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="app.suppliercategory",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-is_featured", "name"],},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["is_read", "-created_at"],},
        ),
        migrations.CreateModel(
            name="GuestConfirmationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pendente"),
                            ("Confirmed", "Confirmado"),
                            ("Refused", "Recusado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_tokens",
                        to="app.guest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guest",
            name="wedding_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="app.userweddingprofile",
            ),
        ),
        migrations.CreateModel(
            name="GiftListShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wedding_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_share_token",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home", "Casa"),
                            ("travel", "Viagem"),
                            ("money", "Dinheiro"),
                            ("other", "Outros"),
                            ("experience", "Experiência"),
                            ("charity", "Caridade"),
                            ("electronics", "Eletrônicos"),
                            ("furniture", "Móveis"),
                            ("kitchen", "Cozinha"),
                            ("clothing", "Roupas"),
                            ("books", "Livros"),
                            ("toys", "Brinquedos"),
                            ("jewelry", "Joias"),
                            ("decor", "Decoração"),
                            ("other", "Outro"),
                            ("gift_card", "Cartão Presente"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True, help_text="Cloudinary image URL", null=True
                    ),
                ),
                (
                    "image_public_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or CSS class", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponível"),
                            ("purchased", "Comprado"),
                            ("reserved", "Reservado"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "purchased_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who purchased",
                        max_length=120,
                    ),
                ),
                ("purchase_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reserved_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who reserved",
                        max_length=120,
                    ),
                ),
                ("reserved_message", models.TextField(blank=True)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        help_text="Product code or identifier",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTaskShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="app.checklisttask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTaskNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="app.checklisttask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="checklist_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="app.checklisttask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_user", models.BooleanField(default=True)),
                ("content", models.TextField()),
                (
                    "thinking_content",
                    models.TextField(
                        blank=True,
                        help_text="Conteúdo do pensamento/raciocínio da IA",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.usersession",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="customuser",
            name="settings",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="app.usersettings",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="WeddingSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_hired", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "negotiated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("contract_date", models.DateField(blank=True, null=True)),
                ("wedding_delivery_date", models.DateField(blank=True, null=True)),
                ("contract_file_url", models.URLField(blank=True)),
                (
                    "contract_file_public_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUOTING", "Cotando"),
                            ("NEGOTIATING", "Negociando"),
                            ("HIRED", "Contratado"),
                            ("PAID", "Pago"),
                            ("CANCELED", "Cancelado"),
                        ],
                        default="QUOTING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_suppliers",
                        to="app.supplier",
                    ),
                ),
                (
                    "wedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_suppliers",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_favorite", "-updated_at"],
                "unique_together": {("wedding", "supplier")},
            },
        ),
        migrations.CreateModel(
            name="UserQuestionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_answer", models.CharField(max_length=10)),
                ("is_correct", models.BooleanField()),
                ("time_spent", models.IntegerField(null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.questionreference",
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usersession",
                    ),
                ),
            ],
            options={
                "db_table": "user_question_history",
                "unique_together": {("user_session", "question")},
            },
        ),
    ]
