# Generated by Django 4.2 on 2025-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("noivo", "Noivo(a)"),
                    ("convidado", "Convidado"),
                    ("admin", "Admin"),
                ],
                default="noivo",
                max_length=20,
            ),
        ),
    ]
