# Generated by Django 4.2 on 2026-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="instagram",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier", name="website", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="suppliercategory",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="suppliercategory",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
