# Generated by Django 4.2 on 2025-06-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWeddingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome_noivo", models.CharField(blank=True, max_length=100)),
                ("descricao_noivo", models.TextField(blank=True)),
                ("facebook_noivo", models.CharField(blank=True, max_length=255)),
                ("instagram_noivo", models.CharField(blank=True, max_length=255)),
                ("email_noivo", models.EmailField(blank=True, max_length=254)),
                ("nome_noiva", models.CharField(blank=True, max_length=100)),
                ("descricao_noiva", models.TextField(blank=True)),
                ("facebook_noiva", models.CharField(blank=True, max_length=255)),
                ("instagram_noiva", models.CharField(blank=True, max_length=255)),
                ("email_noiva", models.EmailField(blank=True, max_length=254)),
                ("data_casamento", models.DateField(blank=True, null=True)),
                ("hora_casamento", models.TimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=50)),
                ("cor_principal", models.CharField(blank=True, max_length=50)),
                ("frase_casal", models.CharField(blank=True, max_length=255)),
                ("fotos_amigos", models.JSONField(blank=True, default=list)),
                ("fotos_familia", models.JSONField(blank=True, default=list)),
                ("fotos_diversas", models.JSONField(blank=True, default=list)),
                ("historia", models.CharField(blank=True, max_length=400)),
                ("padrinhos", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
