# Generated by Django 4.2 on 2025-06-12 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userweddingprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template", models.CharField(default="classico", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicado"),
                            ("inactive", "Inativo"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("url_slug", models.SlugField(max_length=64, unique=True)),
                ("cover_photo", models.URLField(blank=True, null=True)),
                ("palette", models.CharField(blank=True, max_length=50)),
                ("font", models.CharField(blank=True, max_length=50)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("rsvp_count", models.PositiveIntegerField(default=0)),
                ("rsvp_conversion", models.FloatField(default=0.0)),
                ("last_visitor", models.CharField(blank=True, max_length=100)),
                ("last_visitor_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_site",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="WeddingSiteHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="app.weddingsite",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
