# Generated by Django 4.2 on 2026-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_productcatalog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productcatalog",
            new_name="app_product_store_46a9ad_idx",
            old_name="app_product_store_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="productcatalog",
            new_name="app_product_search__17ab40_idx",
            old_name="app_product_search_idx",
        ),
        migrations.AlterField(
            model_name="gift",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
