# Generated by Django 4.2 on 2026-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0004_rename_app_product_store_cat_idx_app_product_store_46a9ad_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="image",
            field=models.URLField(
                blank=True, help_text="Cloudinary image URL", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="photo_url",
            field=models.URLField(
                blank=True,
                help_text="URL da foto do convidado (Cloudinary)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="product_url",
            field=models.URLField(db_index=True, max_length=500, unique=True),
        ),
    ]
