# Generated by Django 4.2 on 2025-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_weddingsite_weddingsitehistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="weddingsite", name="content",),
        migrations.AddField(
            model_name="userweddingprofile",
            name="cep",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userweddingprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userweddingprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="about_us",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="bride_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="countdown",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="gallery",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="groom_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="local",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="map",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="postalcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="rsvp_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="social",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="wedding_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weddingsite",
            name="wedding_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
