# Generated by Django 4.2 on 2025-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_weddingsite_content_userweddingprofile_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userweddingprofile",
            name="historia",
            field=models.TextField(blank=True),
        ),
    ]
