# Generated by Django 4.2 on 2025-06-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_userweddingprofile_historia"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("id_cloudinary", models.CharField(max_length=255)),
                ("folder", models.CharField(blank=True, max_length=100)),
                ("in_use", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="weddingsite",
            name="cover_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_for_sites",
                to="app.weddingimage",
            ),
        ),
    ]
