# Generated by Django 4.2 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_expand_url_fields_for_gifts_and_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gift",
            name="purchased_by",
            field=models.CharField(
                blank=True, help_text="Name of the person who purchased", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="reserved_by",
            field=models.CharField(
                blank=True, help_text="Name of the person who reserved", max_length=255
            ),
        ),
    ]
