# Generated by Django 4.2 on 2025-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_weddingimage_alter_weddingsite_cover_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="weddingsite", name="gallery",),
        migrations.AddField(
            model_name="weddingsite",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="gallery_for_sites", to="app.weddingimage"
            ),
        ),
    ]
