# Generated by Django 4.2 on 2025-06-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_weddingsite_gallery_weddingsite_gallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weddingsitehistory", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="weddingsitehistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criação"),
                    ("edit", "Edição"),
                    ("publish", "Publicação"),
                    ("unpublish", "Despublicação"),
                    ("delete", "Exclusão"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weddingsitehistory", name="snapshot", field=models.JSONField(),
        ),
    ]
