# Generated by Django 4.2 on 2026-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_productcatalog_is_essential_template"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productcatalog",
            new_name="app_product_is_esse_d95e0f_idx",
            old_name="app_product_is_essential_idx",
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=2048, verbose_name="URL da imagem"
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço sugerido",
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="product_url",
            field=models.URLField(
                db_index=True,
                max_length=2048,
                unique=True,
                verbose_name="URL do produto",
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
    ]
