# Generated by Django 4.2 on 2026-05-26

from django.db import migrations, models
from django.db.models import Count, Min, Q


def dedupe_gift_product_codes(apps, schema_editor):
    Gift = apps.get_model('app', 'Gift')

    duplicate_groups = (
        Gift.objects.exclude(product_code='')
        .values('wedding_profile_id', 'product_code')
        .annotate(keep_id=Min('id'), total=Count('id'))
        .filter(total__gt=1)
    )

    for group in duplicate_groups.iterator():
        (
            Gift.objects.filter(
                wedding_profile_id=group['wedding_profile_id'],
                product_code=group['product_code'],
            )
            .exclude(id=group['keep_id'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_app_product_is_essential_idx_app_product_is_esse_d95e0f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_gift_product_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='gift',
            constraint=models.UniqueConstraint(
                fields=['wedding_profile', 'product_code'],
                condition=~Q(product_code=''),
                name='unique_gift_product_code_per_wedding',
            ),
        ),
    ]
