# Generated by Django 4.2 on 2025-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_checklisttask_checklisttaskshare_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttask",
            name="days_before_event",
            field=models.IntegerField(
                blank=True,
                help_text="Dias antes do evento para agrupar no frontend",
                null=True,
            ),
        ),
    ]
