# Generated by Django 4.2 on 2026-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_dedupe_basic_gifts_and_add_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="product_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Product code or identifier",
                max_length=100,
                null=True,
            ),
        ),
    ]
