# Generated by Django 4.2 on 2025-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="acompanhantes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="alergias",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
