# Generated by Django 4.2 on 2026-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_customuser_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_steps",
            field=models.BooleanField(default=False),
        ),
    ]
