# Generated by Django 4.2 on 2026-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_customuser_first_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
