# Generated by Django 4.2 on 2025-06-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_guest_acompanhantes_guest_alergias_guest_observacoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("link", models.URLField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("casa", "Casa"),
                            ("viagem", "Viagem"),
                            ("dinheiro", "Dinheiro"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="gifts/"),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone ou classe CSS",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("comprado", "Comprado"),
                            ("reservado", "Reservado"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                ("data_compra", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_produto",
                    models.CharField(
                        blank=True,
                        help_text="Código ou identificador do produto",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "comprado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_comprados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
        ),
    ]
