# Generated by Django 4.2 on 2025-06-25 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_gift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gift", old_name="criado_em", new_name="created_at",
        ),
        migrations.RenameField(model_name="gift", old_name="nome", new_name="name",),
        migrations.RenameField(
            model_name="gift", old_name="data_compra", new_name="purchase_date",
        ),
        migrations.RenameField(
            model_name="gift", old_name="atualizado_em", new_name="updated_at",
        ),
        migrations.RenameField(model_name="gift", old_name="valor", new_name="value",),
        migrations.RemoveField(model_name="gift", name="categoria",),
        migrations.RemoveField(model_name="gift", name="codigo_produto",),
        migrations.RemoveField(model_name="gift", name="comprado_por",),
        migrations.RemoveField(model_name="gift", name="descricao",),
        migrations.RemoveField(model_name="gift", name="icone",),
        migrations.RemoveField(model_name="gift", name="imagem",),
        migrations.AddField(
            model_name="gift",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Casa"),
                    ("travel", "Viagem"),
                    ("money", "Dinheiro"),
                    ("other", "Outros"),
                ],
                default=datetime.datetime(
                    2025, 6, 25, 16, 51, 23, 457762, tzinfo=datetime.timezone.utc
                ),
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gift", name="description", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Icon name or CSS class", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="image",
            field=models.URLField(
                blank=True, help_text="Cloudinary image URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="product_code",
            field=models.CharField(
                blank=True, help_text="Product code or identifier", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="purchased_by",
            field=models.CharField(
                blank=True, help_text="Name of the person who purchased", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponível"),
                    ("purchased", "Comprado"),
                    ("reserved", "Reservado"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
