# Generated by Django 4.2 on 2025-06-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_rename_criado_em_gift_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftListShareToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wedding_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_share_token",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
        ),
    ]
