# Generated by Django 5.2.3 on 2026-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_guest_status_presenca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="category",
            field=models.CharField(
                choices=[
                    ("home", "Casa"),
                    ("travel", "Viagem"),
                    ("money", "Dinheiro"),
                    ("other", "Outros"),
                    ("experience", "Experiência"),
                    ("charity", "Caridade"),
                    ("electronics", "Eletrônicos"),
                    ("furniture", "Móveis"),
                    ("kitchen", "Cozinha"),
                    ("clothing", "Roupas"),
                    ("books", "Livros"),
                    ("toys", "Brinquedos"),
                    ("jewelry", "Joias"),
                    ("decor", "Decoração"),
                    ("other", "Outro"),
                    ("gift_card", "Cartão Presente"),
                ],
                max_length=30,
            ),
        ),
    ]
