# Generated by Django 5.2.3 on 2026-05-16 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_gift_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestConfirmationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pendente"),
                            ("Confirmed", "Confirmado"),
                            ("Refused", "Recusado"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmation_tokens",
                        to="app.guest",
                    ),
                ),
            ],
        ),
    ]
