# Generated by Django 5.2.3 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_guestconfirmationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userweddingprofile",
            name="telefone_noivo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userweddingprofile",
            name="telefone_noiva",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="gift",
            name="reserved_by",
            field=models.CharField(blank=True, help_text="Name of the person who reserved", max_length=120),
        ),
        migrations.AddField(
            model_name="gift",
            name="reserved_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="reserved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
