# Generated by Copilot on 2026-05-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


SUPPLIER_CATEGORIES = [
    'Buffet',
    'Cerimonial',
    'Fotografia',
    'Filmagem',
    'Música',
    'Decoração',
    'Espaço',
    'Convites',
    'Bolo',
    'Doces',
    'Vestido',
    'Lua de mel',
]


def seed_supplier_categories(apps, schema_editor):
    SupplierCategory = apps.get_model('app', 'SupplierCategory')
    for name in SUPPLIER_CATEGORIES:
        SupplierCategory.objects.get_or_create(name=name, defaults={'slug': name.lower().replace(' ', '-')})


def unseed_supplier_categories(apps, schema_editor):
    SupplierCategory = apps.get_model('app', 'SupplierCategory')
    SupplierCategory.objects.filter(name__in=SUPPLIER_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_weddingprofile_phone_fields_and_gift_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('cover_image_url', models.URLField(blank=True)),
                ('cover_image_public_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovado'), ('PENDING', 'Pendente')], default='PENDING', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='app.suppliercategory')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeddingSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hired', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('wedding_delivery_date', models.DateField(blank=True, null=True)),
                ('contract_file_url', models.URLField(blank=True)),
                ('contract_file_public_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUOTING', 'Cotando'), ('NEGOTIATING', 'Negociando'), ('HIRED', 'Contratado'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado')], default='QUOTING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_suppliers', to='app.supplier')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_suppliers', to='app.userweddingprofile')),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
                'unique_together': {('wedding', 'supplier')},
            },
        ),
        migrations.RunPython(seed_supplier_categories, unseed_supplier_categories),
    ]
