# Generated by Django 5.2.3 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_supplier_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
