from django.db import migrations, models


def mark_user_suppliers_as_solo(apps, schema_editor):
    Supplier = apps.get_model('app', 'Supplier')
    Supplier.objects.filter(created_by_user__isnull=False).update(visibility='SOLO')


def unmark_user_suppliers_as_solo(apps, schema_editor):
    Supplier = apps.get_model('app', 'Supplier')
    Supplier.objects.filter(created_by_user__isnull=False).update(visibility='GLOBAL')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='visibility',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('SOLO', 'Solo')], default='GLOBAL', max_length=20),
        ),
        migrations.RunPython(mark_user_suppliers_as_solo, unmark_user_suppliers_as_solo),
    ]# Generated by Django 5.2.3 on 2026-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_supplier_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="visibility",
            field=models.CharField(
                choices=[("GLOBAL", "Global"), ("SOLO", "Solo")],
                default="GLOBAL",
                max_length=20,
            ),
        ),
    ]
