# Generated by Django 5.2.3 on 2026-05-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_supplier_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklisttask",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notas adicionais para a tarefa"
            ),
        ),
    ]
