# Generated by Django 5.2.3 on 2026-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_gift_image_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="wedding_partner_role",
            field=models.CharField(
                blank=True,
                choices=[("noivo", "Noivo(a)"), ("noiva", "Noiva")],
                max_length=10,
                null=True,
            ),
        ),
    ]
