# Generated by Django 5.2.3 on 2026-05-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_customuser_wedding_partner_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_style", models.CharField(blank=True, max_length=50)),
                ("wedding_size", models.CharField(blank=True, max_length=50)),
                ("dress_code", models.CharField(blank=True, max_length=50)),
                ("palette", models.JSONField(blank=True, default=list)),
                (
                    "wedding_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_identity",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
