# Generated by Django 4.2 on 2026-05-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_weddingidentity_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeddingIdentityInspiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(max_length=500)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("query", models.CharField(blank=True, max_length=255)),
                ("selected_style", models.CharField(blank=True, max_length=50)),
                ("dress_code", models.CharField(blank=True, max_length=50)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "wedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspirations",
                        to="app.userweddingprofile",
                    ),
                ),
            ],
            options={"ordering": ["-is_favorite", "-is_liked", "-created_at"],},
        ),
    ]
