PRODUCTS_BY_CATEGORY = {
    'cozinha': [
        'air fryer 2l',
        'air fryer 3l',
        'air fryer 4l',
        'air fryer 6l',
        'air fryer 12l',
        'air fryer digital',
        'panela de pressao eletrica',
        'panela eletrica de arroz',
        'cafeteira eletrica simples',
        'cafeteira expresso premium',
        'liquidificador 1000w',
        'liquidificador premium vidro',
        'processador de alimentos',
        'batedeira planetaria',
        'fogao 4 bocas inox',
        'fogao 6 bocas premium',
        'microondas 20 litros',
        'microondas inox 30 litros',
        'jogo de panelas antiaderente',
        'jogo de facas cozinha',
        'conjunto de utensilios cozinha',
    ],
    'eletrodomesticos': [
        'geladeira frost free',
        'geladeira inverse',
        'geladeira side by side',
        'maquina de lavar 8kg',
        'maquina de lavar 12kg',
        'maquina de lavar 15kg',
        'lava e seca premium',
        'secadora de roupas',
        'ar condicionado 12000 btus',
        'ar condicionado inverter',
        'ventilador de coluna',
        'aspirador de po vertical',
        'aspirador robô',
        'bebedouro de agua',
        'forno eletrico de bancada',
        'frigobar',
        'purificador de agua',
        'desumidificador de ambiente',
        'extrator de suco',
    ],
    'moveis': [
        'sofa retratil',
        'sofa 3 lugares',
        'sofa 2 lugares',
        'rack para tv',
        'painel para tv',
        'mesa de jantar 4 lugares',
        'mesa de jantar 6 lugares',
        'cadeira de jantar estofada',
        'cama box casal',
        'cama queen',
        'cama king',
        'guarda roupa casal',
        'comoda 6 gavetas',
        'aparador moderno',
        'poltrona decorativa',
        'mesa lateral',
        'sapateira',
    ],
    'quarto': [
        'jogo de cama casal',
        'jogo de cama queen',
        'edredom casal',
        'edredom queen',
        'travesseiro ortopedico',
        'travesseiro premium',
        'protetor de colchao impermeavel',
        'cobertor casal',
        'cobertor queen',
        'colcha casal',
        'porta travesseiro',
        'kit enxoval casal',
        'almofada decorativa quarto',
        'luminaria de cabeceira',
        'abajur moderno',
        'cortina blackout quarto',
        'manta decorativa cama',
        'orelha de cama',
    ],
    'banheiro': [
        'jogo de toalhas 2 pecas',
        'jogo de toalhas 5 pecas',
        'toalha banho premium',
        'toalha rosto algodao',
        'tapete banheiro antiderrapante',
        'kit porta sabonete banheiro',
        'kit banheiro 4 pecas',
        'espelho banheiro',
        'toalheiro inox',
        'lixeira banheiro inox',
        'cesto de roupa suja',
        'organizador banheiro',
        'rodo banheiro',
        'chuveiro eletrico',
        'ducha pressurizada',
        'toalha de piso',
        'porta papel higienico',
        'dispenser sabonete liquido',
    ],
    'decoracao': [
        'quadro decorativo',
        'placa decorativa casal',
        'vaso decorativo',
        'espelho decorativo',
        'luminaria decorativa',
        'abajur decorativo',
        'vela aromatica premium',
        'aromatizador de ambiente',
        'difusor de ambiente',
        'porta retrato',
        'escultura decorativa',
        'objetos decorativos sala',
        'cesta decorativa',
        'relógio de parede decorativo',
        'flores artificiais premium',
        'painel decorativo',
        'almofada decorativa',
        'bandeja decorativa',
    ],
    'tecnologia': [
        'smart tv 43',
        'smart tv 55',
        'smart tv 65',
        'notebook i5',
        'notebook i7',
        'tablet 10 polegadas',
        'smartphone intermediario',
        'smartphone premium',
        'smartwatch',
        'fone bluetooth',
        'caixa de som bluetooth',
        'console videogame',
        'roteador wifi mesh',
        'desktop gamer',
        'monitor 27 polegadas',
        'teclado mecanico',
        'mouse sem fio',
        'carregador por indução',
    ],
    'lavanderia': [
        'ferro de passar',
        'ferro a vapor',
        'tabua de passar',
        'varal de chao',
        'varal de parede',
        'cesto organizador roupa',
        'sabao liquido roupas',
        'amaciante premium',
        'passadeira a vapor',
        'vaporizador de roupas',
        'lavadora de alta pressao',
        'escova para roupas',
        'kit lavanderia',
        'organizadores de lavanderia',
        'saco para roupa suja',
        'potes para sabao',
        'cabideiro para lavanderia',
        'clorador para roupas',
    ],
    'lua_de_mel': [
        'mala de viagem pequena',
        'mala de viagem media',
        'mala de viagem grande',
        'jogo de malas 2 pecas',
        'mochila de viagem',
        'frasqueira de viagem',
        'necessaire de viagem',
        'travesseiro de pescoco',
        'almofada de viagem',
        'cadeado para mala',
        'kit organizador de mala',
        'bolsa de bordo',
        'adaptador universal de tomada',
        'power bank',
        'camera instantanea',
        'camera action',
        'mochila antifurto',
        'bolsa tiracolo viagem',
        'alexa',
        'assistente virtual',
        'kindle',
        'fire stick',
        'fones de ouvido com cancelamento de ruido',
        'caixa de som bluetooth portátil',
    ],
}

PRODUCTS_TO_SEARCH = [term for products in PRODUCTS_BY_CATEGORY.values() for term in products]
