from django.core.management.base import BaseCommand
from django.utils.text import slugify
from app.models import SupplierCategory, Supplier  # Altere 'seu_app' para o nome do seu app

class Command(BaseCommand):
    help = "Gera a lista interna de categorias e 50 fornecedores reais de Campina Grande e região"

    def handle(self, *args, **options):
        # 1. Garantir que as categorias existam
        categories_list = [
            'Buffet', 'Cerimonial', 'Fotografia', 'Filmagem', 'Música',
            'Decoração', 'Espaço', 'Convites', 'Bolo', 'Doces', 'Vestido', 'Lua de mel', 'Beleza da Noiva',
            'Outros', 'Open Bar', 'Storymaker', 'Estrutura'
        ]
        
        category_objects = {}
        for cat_name in categories_list:
            category, created = SupplierCategory.objects.get_or_create(
                name=cat_name,
                defaults={'slug': slugify(cat_name)}
            )
            category_objects[cat_name] = category
            if created:
                self.stdout.write(self.style.SUCCESS(f"Categoria criada: {cat_name}"))

        suppliers_data = [
            # --- Buffet ---
            {"name": "Le mel buffet e eventos", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98855-2219", "whatsapp": "+5583988552219", "instagram": "https://www.instagram.com/lemelbuffeteeventos/",
             "address": "R. José Gonçalves de Melo, 52 - Universitário, Campina Grande - PB, 58429-085", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/le_mel_ocdobe.jpg"},
            {"name": "Regallier Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99145-8987", "whatsapp": "+5583991458987", "instagram": "https://www.instagram.com/regallierbuffet/",
             "address": "R. Antônio Joaquim Pequeno, 198 - Universitário, Campina Grande - PB, 58429-010", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/385343367_697956448457320_3321118921925238988_n_g6cdvk.jpg"},
            {"name": "Buffet Santana", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99837-0099", "whatsapp": "+5583998370099", "instagram": "https://www.instagram.com/buffetsantana_cg/",
             "address": "R. Damasco, 350 - Santa Rosa, Campina Grande - PB, 58416-580", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/65126444_1676465889163900_2173456685333479424_n_ywwsvu.jpg"},
            {"name": "Inácio Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98638-9551", "whatsapp": "+5583986389551", "instagram": "https://www.instagram.com/inaciobuffet/",
             "address": "Av. Marechal Floriano Peixoto, 1510 - Centro, Campina Grande - PB, 58400-165", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779121221/img-354439-20161117143003_s9x4fg.png"},
            {"name": "The Buffet Festas", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98801-4467", "whatsapp": "+5583988014467", "instagram": "https://www.instagram.com/the_buffet_festas/",
             "address": "R. Aprígio Veloso, 815 - Universitário, Campina Grande - PB, 58429-140", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779121222/273996584_1371931693226867_5416905905595167435_n_hzdrbk.jpg"},
            {"name": "D'gust Restaurante e Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98808-5583", "whatsapp": "+5583988085583", "instagram": "https://www.instagram.com/dgust.cg/",
             "address": "R. Rio de Janeiro, 484 - Liberdade, Campina Grande - PB, 58414-080", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779121221/651924825_18094720676007419_6720821973517417883_n_mribmh.jpg"},
            {"name": "Casa Chez Vous", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99922-6588", "whatsapp": "+5583999226588", "instagram": "https://www.instagram.com/buffetchezvous/",
             "address": "R. Vidal de Negreiros, 164 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779121221/03e7d3de-39c5-458d-843d-81f005ea8b47_casa2_ad6stv.webp"},
            {"name": "La Costa Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98680-4681", "whatsapp": "+5583986804681", "instagram": "https://www.instagram.com/lacostabuffet/",
             "address": "R. Agrimensor José de Brito, 301 - Lauritzen, Campina Grande - PB, 58401-396", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779121318/116797460_2720874268149267_4481032255659531553_n_lfdxdy.jpg"},
            {"name": "Keyla Khenia", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99136-1316", "whatsapp": "+5583991361316", "instagram": "https://www.instagram.com/keylakheniabuffet/",
             "address": "R. José Alves Sobrinho, 40 - Jardim TavaresCampina Grande - PB, 58402-063", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/640416438_18326435884216326_2010988915822506558_n_lky2bi.jpg"},
            {"name": "Anabela Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98863-9285", "whatsapp": "+5583988639285", "instagram": "https://www.instagram.com/anabelabuffet/", 
             "address": "R. José Gonçalves de Melo, 52 - Universitário, Campina Grande - PB, 58429-085", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779196504/491443378_2488389194831827_7266246361808484329_n_ycxneb.jpg"},
            {"name": "Imbituba Gastronomia", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99833-0098", "whatsapp": "+5583998330098", "instagram": "https://www.instagram.com/imbitubagastronomia/", 
             "address": "Av. Paris, 3416 - Campina Grande, PB, 58115-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779196504/449600842_1008862990796207_5569285489724994002_n_ii5emm.jpg"},
            {"name": "Arnaldo Neto Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98647-1715", "whatsapp": "+5583986471715", "instagram": "https://www.instagram.com/arnaldo.neto.x/", 
             "address": "R. Vidal de Negreiros, 164 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779196504/615852947_18109196191632925_2906394922952043919_n_grykei.jpg"},
            {"name": "Betty Recepções e Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99322-8758", "whatsapp": "+5583993228758", "instagram": "https://www.instagram.com/bettyrecepcoes/", 
             "address": "R. Vidal de Negreiros, 164 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779196503/420051298_690143579869565_5561601490795192014_n_z4c0hd.jpg"},
            {"name": "Rosendo Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98663-1973", "whatsapp": "+5583986631973", "instagram": "https://www.instagram.com/rosendobuffet_/", 
             "address": "R. Vidal de Negreiros, 164 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779196504/403927638_681552240425153_2350321941890761505_n_yy77yw.jpg"},


            # --- Cerimonial ---
            {"name": "Neide Cerimonial E Eventos", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99991-0326", "whatsapp": "+5583999910326", "website": "https://www.casamentos.com.br/cerimonialista/neide-cerimonial-e-eventos--e120424",
              "instagram": "https://www.instagram.com/neidefreitascerimonial/",  "address": "R. João da Mata, 407 - SALA 101 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952435/55aa5841-c5f3-4549-a646-ee764488ba12_WhatsApp-Image-2024-05-14-at-12.43.41_m0pe3a.webp"},
            {"name": "Tulip Cerimoniais", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98874-9169", "whatsapp": "+558388749169", 
             "instagram": "https://www.instagram.com/tulipcerimoniais/", "address": "R. João da Mata, 407 - SALA 101 - Centro, Campina Grande - PB, 58400-245", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952540/555444643_18431415187100249_7666184394088624231_n_m0lb1t.jpg"},
            {"name": "Manu Coutinho Assessoria e Cerimonial", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99114-5944", "whatsapp": "+5583991145944", "instagram": "https://www.instagram.com/manucoutinhocerimonial/",
             "address": "R. Aprígio Nepomuceno, 1100 - Sala 105 - Cruzeiro, Campina Grande - PB, 58415-460", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123899/unnamed_tlwpi6.webp"},
            {"name": "Jaqueline Cavalcanti Cerimonialista", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99614-1710", "whatsapp": "+5583996141710", "instagram": "https://www.instagram.com/jaquelinecavalcanti/",
             "address": "R. Gasparino Barreto, 657 - Cruzeiro, Campina Grande - PB, 58415-430", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123899/Captura_de_tela_2026-05-18_140442_vgrnt8.png"},
            {"name": "Encantar Assessoria & Eventos", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98826-3316", "whatsapp": "+5583988263316", "instagram": "https://www.instagram.com/encantarcerimonial/",
             "address": "R. Carlos Alberto Souza, 341 - Sala 02 - Catolé, Campina Grande - PB, 58410-546", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123016/509288899_9735702113223165_2630271544618236856_n_h85m5l.jpg"},
            {"name": "Celebrare Assessoria e Cerimonial", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99911-8686", "whatsapp": "+5564992259204", "instagram": "https://www.instagram.com/celebrareassessoriacerimonial/",
             "address": "R. Elvira Almeida Castro, 155 - Centro, Campina Grande - PB, 58400-243", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123016/Design_sem_nome_icgthb.png"},
            {"name": "De Pontes Assessoria e Cerimonial", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98811-3121", "whatsapp": "+5583988113121", "instagram": "https://www.instagram.com/depontescerimonial/",
             "address": "R. Prof. Ariel de Oliveira, 385 - Catolé, Campina Grande - PB, 58410-435", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123016/359514549_807912064668736_8046614333545010943_n_pqg1x9.jpg"},
            {"name": "Priscila Oliveira Cerimonial", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99109-6909", "whatsapp": "+5583991096909", "instagram": "https://www.instagram.com/priscilaoliveiracerimonial/",
             "address": "R. Vigário Calixto, 1395 - Catolé, Campina Grande - PB, 58410-340", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123015/11931135_404584056412175_3313661_a_evoavo.jpg"},
            {"name": "Reprise Eventu's Assessoria", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98191-6039", "whatsapp": "+5583981916039", "instagram": "https://www.instagram.com/repriseeventus/",
             "address": "R. Papa João Paulo I, 210 - Cruzeiro, Campina Grande - PB, 58415-420", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123016/43547699_1940806699549001_8190755808909197312_n_qmuz6x.jpg"},
            {"name": "Dois é Par - Assessoria de Eventos", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99888-5916", "whatsapp": "+5583998885916", "instagram": "https://www.instagram.com/doisepar.assessoria/",
             "address": "R. Washington Alves Gomes, 385 - Casa J - Catolé, Campina Grande - PB, 58410-613", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123015/78ad51bc79a64715d59538988b2a0598_zxzqov.png"},
            {"name": "Santtos Assessoria e Cerimonial", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98742-9797", "whatsapp": "+5583987429797", "instagram": "https://www.instagram.com/santtos_assessoria_cerimonial/",
             "address": "R. João Machado, 267 - Centro, Campina Grande - PB, 58400-246", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123015/Captura_de_tela_2026-05-18_134535_qkegbt.png"},
            {"name": "Realizar Cerimonial e Assessoria", "category": "Cerimonial", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99982-5399", "whatsapp": "+5583999825399", "instagram": "https://www.instagram.com/realizarcerimonial_/",
             "address": "R. Ascendino Toscano Brito, 648 - Alto Branco, Campina Grande - PB, 58401-565", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779123014/unnamed_ommqne.webp"},


            # --- Fotografia ---
             {"name": "Torrani Produtora", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99627-8774", "whatsapp": "+5583996278774", "instagram": "https://www.instagram.com/torraniprodutora/",
             "address": "R. Ana Vilar, 348 - Cruzeiro, Campina Grande - PB, 58415-625", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/610073273_18547758601000674_6454687948680570203_n_skoceh.jpg"},
            {"name": "Victor Luis Fotografias", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99108-0691", "whatsapp": "+5583991080691", "instagram": "https://www.instagram.com/vluisphoto/",
             "address": "R. Otacílio Nepomuceno, 203 - Catolé, Campina Grande - PB, 58410-160", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/400x100_4fe8aae6-4b0a-4cbc-9602-ba136cdca31a_zixigs.png"},
            {"name": "Tomaz Fotografias", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99881-9640", "whatsapp": "+5583998819640", "instagram": "https://www.instagram.com/tomazfotografias/",
             "address": "R. Dr. Severino Cruz, 285 - Centro, Campina Grande - PB, 58400-222", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/marca_jbqhlg.png"},
            {"name": "Recordare Fotografias", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99632-8743", "whatsapp": "+5583996328743", "instagram": "https://www.instagram.com/recordarefotografias/",
             "address": "Empresarial Falcão - R. Aprígio Nepomuceno, 1100 - Sala 211 - Jardim Paulistano, Campina Grande - PB, 58414-370", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/207014341_978599889555833_5305692939934072392_n_tmdchp.jpg"},
            {"name": "Studio Virgínia Neiva", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 3322-3583", "whatsapp": "+558333223583", "instagram": "https://www.instagram.com/studiovirginianeiva/",
             "address": "R. Raimundo Alves da Silva, 228 - Conceição, Campina Grande - PB, 58401-276", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/13398700_1553174621644237_1229922040_a_mock1u.jpg"},
            {"name": "Photo Studio JR", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98723-6018", "whatsapp": "+5583987236018", "instagram": "https://www.instagram.com/photostudio.jr/",
             "address": "R. Artur Ferreira de Castro, 80 - 1° Andar - Catolé, Campina Grande - PB, 58410-733", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/351431825_155994214127241_6455019904015889124_n_f1pesc.jpg"},
            {"name": "Anne Karoline Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99671-1008", "whatsapp": "+5583996711008", "instagram": "https://www.instagram.com/annekarolinefotografia/",
             "address": "R. Antenor Navarro, 913c - Prata, Campina Grande - PB, 58400-012", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/anne_pbufv3.jpg"},
            {"name": "Rayssa Daniele Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99331-4555", "whatsapp": "+5583993314555", "instagram": "https://www.instagram.com/rayssadanielefotografia/",
             "address": "R. Francisco Ernesto do Rêgo, 1904 - Jardim Paulistano, Campina Grande - PB, 58415-285", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/rayssa_sm8arz.jpg"},
            {"name": "Vitorya Fotografias Prime", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 3322-6748", "whatsapp": "+558333226748", "instagram": "https://www.instagram.com/vitoryafotografias/",
             "address": "R. Afonso Campos, 167 - Centro, Campina Grande - PB, 58400-235", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/356208850_2237276136457246_4136761256281865169_n_bph1rx.jpg"},
            {"name": "Bewerlly Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99802-2753", "whatsapp": "+5583998022753", "instagram": "https://www.instagram.com/bewerllyfotografia/",
             "address": "R. Roberto Cavalcante Albuquerque, 890 - Jardim Paulistano, Campina Grande - PB, 58415-145", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/bewerly_funoo0.jpg"},
            {"name": "Leydson Jackson", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98720-4025", "whatsapp": "+5583987204025", "instagram": "https://www.instagram.com/leydsonjackson_/",
             "address": "R. Papa Paulo Sexto - Nova Brasília, Campina Grande - PB, 58406-800", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/Captura_de_tela_2026-05-18_214844_q0yhs9.png"},
            {"name": "Estúdio Rennan Oliveira", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99882-3110", "whatsapp": "+5583998823110", "instagram": "https://www.instagram.com/estudiorennanoliveira/",
             "address": "Heron Marinho Empresarial - R. José Bernardino, 97 - Sala 804 - Vila Cabral, Campina Grande - PB, 58408-027", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/503480082_18072297641311170_6673571489406586636_n_aadi6g.jpg"},
            {"name": "Studio Marta Mello", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99909-9068", "whatsapp": "+5583999099068", "instagram": "https://www.instagram.com/studiomartamello/",
             "address": "R. Manoel Sérgio Oliveira, 35 - Conceição, Campina Grande - PB, 58401-290", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153412/627563912_18395651518179737_3280271034614685525_n_vlkkbc.jpg"},
            {"name": "André Almeida Fotografias", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98752-0603", "whatsapp": "+5583987520603", "instagram": "https://www.instagram.com/andrealmeidafotografias/",
             "address": "Rua Mamede Moisés Raia, 40 - Monte Castelo, Campina Grande - PB, 58407-030", "cover_image_url": ""},
            {"name": "Studio Jéssica Azevedo", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99800-8278", "whatsapp": "+5583998008278", "instagram": "https://www.instagram.com/jessicaazevedofotografia/",
             "address": "R. Valeriano Ferreira de Melo, 220 - Sandra Cavalcante, Campina Grande - PB, 58410-865", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/310172062_1524786231308849_7515196109560985458_n_d2ni8e.jpg"},
            {"name": "Ewerton Mascena - Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99406-9804", "whatsapp": "+5583994069804", "instagram": "https://www.instagram.com/mascena_atelie_fotografico/",
             "address": "Avenida Almirante Barroso, 1980, Cruzeiro, Campina Grande PB, 58416-170", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/evertonmacena_ysslzq.jpg"},
            {"name": "Xico Morais Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99971-8160", "whatsapp": "+5583999718160", "instagram": "https://www.instagram.com/xicomorais/",
             "address": "Avenida Almirante Barroso, 1980, Cruzeiro, Campina Grande PB, 58416-170", "cover_image_url": ""},
            {"name": "Breno Nogueira", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99971-8160", "whatsapp": "+5583999718160", "instagram": "https://www.instagram.com/eubrenonogueira/",
             "address": "Avenida Almirante Barroso, 1980, Cruzeiro, Campina Grande PB, 58416-170", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/breno_pftkrh.jpg"},
            {"name": "Johann Nicholas", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98828-4034", "whatsapp": "+5583988284034", "instagram": "https://www.instagram.com/johannnicholas/",
             "address": "Avenida Almirante Barroso, 1980, Cruzeiro, Campina Grande PB, 58416-170", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/639594887_18567918502022524_9152899921747210607_n_lvf2iu.jpg"},
            {"name": "Alice Melo", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98164-1459", "whatsapp": "+5583981641459", "instagram": "https://www.instagram.com/aliccemphoto/",
             "address": "Avenida Almirante Barroso, 1980, Cruzeiro, Campina Grande PB, 58416-170", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779153411/alice_uc2fk2.jpg"},
            {"name": "Isaias Caio", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99982-5399", "whatsapp": "+5583999825399", "instagram": "https://www.instagram.com/iscaiowedding/",
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/iscaio_oy0zib.jpg"},
            {"name": "Camila Ferreira", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99124-4815", "whatsapp": "+5583991244815", "instagram": "https://www.instagram.com/camilamferreira_/",
             "address": "R. do Sol, 1382 - Quarenta", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/camila_zugxyy.jpg"},
            {"name": "Aura Image", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98771-5072", "whatsapp": "+5583987715072", "instagram": "https://www.instagram.com/auraimage_/", 
             "address": "R. do Sol, 1382 - Quarenta", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199003/aura_d6ith0.jpg"},
            {"name": "Senciê Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98876-3753", "whatsapp": "+5583988763753", "instagram": "https://www.instagram.com/senciefotografia/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199003/472447360_1346106083469591_5929137596023846012_n_oatpmk.jpg"},
            {"name": "Candeia Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98764-7537", "whatsapp": "+5583987647537", "instagram": "https://www.instagram.com/candeia.fotografia/",
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199003/logo_candeia_2023_redes_sociais_preto_sldzu3.png"},
            {"name": "Júnior Azevedo Filmes e Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98802-8186", "whatsapp": "+5583988028186", "instagram": "https://www.instagram.com/juniorazevedofilmesefotografia/", 
             "address": "Rua Pastor Robert Reid 234 Mirante, Campina Grande 58407-597", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/juniorazvd_zhm7kp.jpg"},
            {"name": "Wellington Fotógrafo", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/wellington_fotografo/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/wellgtonfot_btwnpl.jpg"},
            {"name": "Entrelaço Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/entrelacofotografia/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/entrelaco_v5xa09.jpg"},
            {"name": "Morada Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99626-4221", "whatsapp": "+5583996264221", "instagram": "https://www.instagram.com/moradafotografia/",
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/morada_erwlkq.jpg"},
            {"name": "Elis Vitória Fotografia", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/elisvitoria.ft/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/elisvitoria_xfedpq.jpg"},
            {"name": "4 Mãos Fotografias", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 2153-5193", "whatsapp": "+558321535193", "instagram": "https://www.instagram.com/4maosfotografias/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/4maos_txebry.jpg"},
            {"name": "Felipe Rocha Foto", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98128-1644", "whatsapp": "+5583981281644", "instagram": "https://www.instagram.com/feliperochafoto/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/Felipe_Rocha_yw6tuf.jpg"},
            {"name": "Kenn Wedding", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/kennwedding/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/kennwedding_pzs0i8.jpg"},
            {"name": "Estúdio Gilmar Batista", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99625-5222", "whatsapp": "+5583996255222", "instagram": "https://www.instagram.com/estudiogilmarbatista/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779199002/gilmarbatista_kclygo.jpg"},

            # --- Filmagem ---
            {"name": "Creative Movies", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98709-3778", "whatsapp": "+5583987093778", "instagram": "https://www.instagram.com/creative.movies/",
             "address": "R. do Sol, 1382 - Quarenta", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/417766001_798778542075428_9047449118160994344_n_dkwghn.jpg"},
            {"name": "Uvva Filmes", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99199-6292", "whatsapp": "+5583991996292", "instagram": "https://www.instagram.com/uvvafilms/",
             "address": "Centro Juridico Ronaldo Cunha Lima - Sala 413 - Estacao Velha, Campina Grande - PB, 58410-050", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/470975086_847648684015064_1391824141658954662_n_zoll6b.jpg"},
            {"name": "FK Vídeo", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99971-4144", "whatsapp": "+5583999714144", "instagram": "https://www.instagram.com/fkvideo/",
             "address": "praça Alfredo Dantas, 62 - sala 04 - Centro, Campina Grande - PB, 58400-107", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/657666312_3444162959074547_763534892003359852_n_eqz9qc.jpg"},
            {"name": "Mais Vídeo Produtora", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99803-0566", "whatsapp": "+5583998030566", "instagram": "https://www.instagram.com/maisvideo/",
             "address": "R. Américo Pôrto, 70a - Lauritzen, Campina Grande - PB, 58401-381", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/24327848_704028286469074_8142073960926806016_n_rglar9.jpg"},
            {"name": "Ruan Filmes", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 2153-6362", "whatsapp": "+558321536362", "instagram": "https://www.instagram.com/ruanfilmes/",
             "address": "R. Olegário Azevedo, 206 58400-346 - São José, Campina Grande - PB, 58400-358", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195325/11856659_619591138143889_1029594620_a_blsepw.jpg"},
            {"name": "Iago Antunes Produtora", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98210-6000", "whatsapp": "+5583982106000", "instagram": "https://www.instagram.com/iagoantunesfilmes/",
             "address": "R. João Suassuna, 102 - Centro, Campina Grande - PB, 58400-120", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/iago_nqgbv8.jpg"},
            {"name": "Lucas Santos Filmmaker", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98637-9471", "whatsapp": "+5583986379471", "instagram": "https://www.instagram.com/lucasgqsantos/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/lucagq_rqizyc.jpg"},
            {"name": "Eternalize Filmes", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98732-6992", "whatsapp": "+5583987326992", "instagram": "https://www.instagram.com/eternalizefilmes/", 
             "address": "R. Aprígio Veloso, 112 - Bodocongó, Campina Grande - PB, 58430-768", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/eternalize_pbtogs.webp"},
            {"name": "H3 Films", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99955-1607", "whatsapp": "+5583999551607", "instagram": "https://www.instagram.com/h3f.ilms/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/h3_unomyt.jpg"},
            {"name": "Moisés Filmes", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98709-3778", "whatsapp": "+5583987093778", "instagram": "https://www.instagram.com/moises.wmv/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/moises_r9ec7s.jpg"},
            {"name": "Tiago V. Souza Filmmaker", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98141-2311", "whatsapp": "+5583981412311", "instagram": "https://www.instagram.com/tiagovsouza/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/tiavovsouza_ifaqrk.jpg"},
            {"name": "LM Films", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99644-7100", "whatsapp": "+5583996447100", "instagram": "https://www.instagram.com/lm.filmss/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/lmfilms_geds9e.jpg"},


            # --- Storymaker ---
            {"name": "Mavi Movies", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/mavi.movies/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/mavistories_rrljnp.jpg"},
             {"name": "Carol Mota Criativa", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99801-8763", "whatsapp": "+5583998018763", "instagram": "https://www.instagram.com/carolmota.creator/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200719/carolmota_vb1t9i.jpg"},
             {"name": "Jaqueline Crizanto Storymaker", "category": "Filmagem", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98642-4159", "whatsapp": "+5583986424159", "instagram": "https://www.instagram.com/jaquelinecrizanto/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200718/jaqueline_xzyc2t.jpg"},
            {"name": "Taynara Costa Storymaker", "category": "Storymaker", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/taynaracostasm/", 
            "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200718/taynaracosta_siuape.jpg"},
            {"name": "Lavínia Cruz", "category": "Storymaker", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99615-7442", "whatsapp": "+5583996157442", "instagram": "https://www.instagram.com/laviniacruz.mov/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200718/laviniacru_yyyk5z.jpg"},
            {"name": "Gabi Vilas Storymaker", "category": "Storymaker", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98817-2678", "whatsapp": "+5583988172678", "instagram": "https://www.instagram.com/gabivilas.vb/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200718/gabivilas_tiu7o8.jpg"},
            {"name": "Duo Take Storymaker", "category": "Storymaker", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99828-5497", "whatsapp": "+5583998285497", "instagram": "https://www.instagram.com/duotakee", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779200718/duotake_uke1mo.jpg"},
             


            # --- Estruturas para Eventos ---
            {"name": "Genilson Estruturas e Eventos", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98874-5506", "whatsapp": "+5583988745506", "instagram": "https://www.instagram.com/genilsonestruturas/",
             "address": "R. Santa Catarina, 2838 - Liberdade, Campina Grande - PB, 58414-055", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/53238341_381690892663871_8744521219581149184_n_xelzbu.jpg"},
            {"name": "Agite Estrutura", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99972-0073", "whatsapp": "+5583999720073", "instagram": "https://www.instagram.com/agite_estrutura/",
             "address": "R. Cícero Jacinto, 60 - Cruzeiro, Campina Grande - PB, 58415-410", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/12716806_176153329424307_1449252470_a_fodvbc.jpg"},
            {"name": "Sucupira Som, Luz e Estruturas", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99973-0123", "whatsapp": "+5583999730123", "instagram": "https://www.instagram.com/sucupiraestruturas/",
             "address": "R. Dr. João Honório de Melo, 118 - Catolé, Campina Grande - PB, 58410-410", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/335924834_593136256041332_5893817878634844708_n_yylhp6.jpg"},
            {"name": "Arte Produções Eventos", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(85) 98140-9721", "whatsapp": "+5585981409721", "instagram": "https://www.instagram.com/arteproducoes/",
             "address": "R. Sebastião Donato, 45 - Centro, Campina Grande - PB, 58400-143", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195055/565470022_18530616871054407_4131956920324256085_n_nrwvgy.jpg"},
            {"name": "Tor Estruturas E Eventos", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98822-4010", "whatsapp": "+5583988224010", "instagram": "https://www.instagram.com/toreventos/",
             "address": "R. Manoel Elías de Castro, 279 - Cruzeiro, Campina Grande - PB, 58415-380", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/384410994_311258788217655_5326609156015788518_n_niaooy.jpg"},
            {"name": "Staff Eventos", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98897-0403", "whatsapp": "+5583988970403", "instagram": "https://www.instagram.com/staffeventos.pb/",
             "address": "R. Maestro Honório, 20C - Prata, Campina Grande - PB, 58400-530", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779195054/561631154_18530653126039959_3096152446309067240_n_lxz0zb.jpg"},
            {"name": "Renovar Eventos", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/renovareventos/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201255/renovar_baiymx.jpg"},
            {"name": "Iluminarth7", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98827-5617", "whatsapp": "+5583988275617", "instagram": "https://www.instagram.com/iluminarth7/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201254/iluminart_uym5cj.jpg"},
            {"name": "Lucas Iluminação de Eventos", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99670-2655", "whatsapp": "+5583996702655", "instagram": "https://www.instagram.com/lucasiluminacao/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201254/lucasilmnao_ei42j1.jpg"},
            {"name": "Amisterdam Sonorização", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/amisterdamsonorizacao/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201254/amsterdan_ldvwdz.jpg"},
            {"name": "Sandro Lira Show Iluminação", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99302-5581", "whatsapp": "+5583993025581", "instagram": "https://www.instagram.com/sandrolira_show/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201254/sandro_h6yf8f.jpg"},
            {"name": "Samy Iluminações", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98723-9507", "whatsapp": "+5583987239507", "instagram": "https://www.instagram.com/samy_iluminacoes/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201254/sami_y61h2i.jpg"},
            

            # --- Música ---
            {"name": "Regis DJ Som e Luz", "category": "Iluminação", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98821-7380", "whatsapp": "+5583988217380", "instagram": "https://www.instagram.com/regisdjcg/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779201255/regisdj_hkynjc.jpg"},
            {"name": "Gerson Freitas DJ", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99691-7314", "whatsapp": "+5583996917314", "instagram": "https://www.instagram.com/gersonfreitasdj/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202911/gersonfretias_vduyz9.jpg"},
            {"name": "Orquestra Andaluz", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99975-3323", "whatsapp": "+5583999753323", "instagram": "https://www.instagram.com/orquestraandaluz/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202912/andaluz_ybznah.jpg"},
            {"name": "Casa Trevo", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99625-8710", "whatsapp": "+5583996258710", "instagram": "https://www.instagram.com/casatrevo/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/casatrevo_pqbnre.jpg"},
            {"name": "EntreNós Acústico", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/entrenos.acustico/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202911/entrenos_lbuwkj.jpg"},
            {"name": "Tereza Castellanos", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/terezacantora/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202911/tereza_ybrxnq.jpg"},
            {"name": "Augusto Arruda", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/eitaugusto/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/augusto_jurwap.jpg"},
            {"name": "Thais Soares", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99635-4908", "whatsapp": "+5583996354908", "instagram": "https://www.instagram.com/euthaissoaress/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/thais_tuvaki.jpg"},
            {"name": "Jorge Ribbas", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/jorgeribbas/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202909/jorgeribas_fi3jhi.jpg"},
            {"name": "Artur VN", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/arturvn/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202911/arturvn_qrxlm5.png"},
            {"name": "Gláucia Almeida Oficial", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/glauciaalmeida_oficial/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/glaucia_rwbflh.jpg"},
            {"name": "Jéssica Vidal", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98716-8223", "whatsapp": "+5583987168223", "instagram": "https://www.instagram.com/jessicaa.vidal/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202909/jessicavdal_ex92ot.jpg"},
            {"name": "Orquestra Voo Livre", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98843-2811", "whatsapp": "+5583988432811", "instagram": "https://www.instagram.com/orquestravoolivre/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/voolivre_drqc5u.jpg"},
            {"name": "Harlann J. Santos Musical", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99975-3323", "whatsapp": "+5583999753323", "instagram": "https://www.instagram.com/harlannjsantos/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/harlann_inmglt.jpg"},
            {"name": "EntreNós Banda", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98196-3250", "whatsapp": "+5583981963250", "instagram": "https://www.instagram.com/entrenos.banda/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/entrenosba_fmp7an.jpg"},
            {"name": "Tinho Shows", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99967-9555", "whatsapp": "+5583999679555", "instagram": "https://www.instagram.com/tinhoshows/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202907/tinhoshow_g16vcv.jpg"},
            {"name": "Cleber Cantor", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cleberecantor/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/cleberca_rdgexb.jpg"},
            {"name": "Emmanuelle Musical", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99376-1897", "whatsapp": "+5583993761897", "instagram": "https://www.instagram.com/emmanuelleadm/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/Emanuelle_oqcdjt.jpg"},
            {"name": "DJ Rony Soares", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99148-2781", "whatsapp": "+5583991482781", "instagram": "https://www.instagram.com/djrony_soares/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202905/djronysoare_ly58jn.jpg"},
            {"name": "DJ Moisés Vitalic", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/djmoisesvitalic/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202904/djmoises_ilyfqx.jpg"},
            {"name": "Erick Silva", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98902-8097", "whatsapp": "+5583989028097", "instagram": "https://www.instagram.com/ericksilvaoficial1/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202904/ericks_qrga2u.jpg"},
            {"name": "DeuseSom Grupo Musical", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99400-4844", "whatsapp": "+5583994004844", "instagram": "https://www.instagram.com/deusesom/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202904/deusesom_kve0n5.jpg"},
            {"name": "Adriano Ezequiel", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99169-5987", "whatsapp": "+5583991695987", "instagram": "https://www.instagram.com/adrianoezzequiel/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202902/adrianoezeq_gk3frx.jpg"},
            {"name": "Bandavollare", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98869-4202", "whatsapp": "+5583988694202", "instagram": "https://www.instagram.com/bandavollare/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/bandavolare_tymv2b.jpg"},
            {"name": "Cantor Edu Almeida", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98838-5836", "whatsapp": "+5583988385836", "instagram": "https://www.instagram.com/cantoredualmeida/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202910/eduardoalmeda_gj4lpk.jpg"},
            {"name": "Forró Lampejo", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98767-0347", "whatsapp": "+5583987670347", "instagram": "https://www.instagram.com/forrolampejo/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202898/forrolampej_fjqmbh.jpg"},
            {"name": "Cantando Sua História", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cantando.sua.historia/",
              "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202908/cantandosuahist_kjz72d.jpg"},
            {"name": "Samuel Nunes", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/samuewmusic/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202902/samuel_cf6xjh.png"},
            {"name": "Marriage Musicais", "category": "Música", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98803-6799", "whatsapp": "+5583988036799", "instagram": "https://www.instagram.com/marriagemusicais/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779202902/marriage_s45xxz.jpg"},
            
            # --- Decoração ---
            {"name": "Iara Ramos Decoração", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/iararamosdecoracao/", 
             "address": "", "cover_image_url": ""},
            {"name": "Juka Dekor", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/juka_dekor/", 
             "address": "", "cover_image_url": ""},
            {"name": "Neguinho Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/neguinhodecoracoes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Encanto de Festa", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/encantodefesta/", 
             "address": "", "cover_image_url": ""},
            {"name": "Josy Medeiros Decor", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/josymedeirosdecor/", 
             "address": "", "cover_image_url": ""},
            {"name": "Alexandre Florista", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/alexandre_florista/", 
             "address": "", "cover_image_url": ""},
            {"name": "Santana Aluguel e Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/aluguelsantana/", 
             "address": "", "cover_image_url": ""},
            {"name": "Decoradora Normanda", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/decoradora_normanda/", 
             "address": "", "cover_image_url": ""},
            {"name": "Clécia Guedes Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cleciaguedes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Almir Decor PB", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/almir_decor.pb/", 
             "address": "", "cover_image_url": ""},
            {"name": "Maria Fita Decor", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/maria.fitadecor/", 
             "address": "", "cover_image_url": ""},
            {"name": "Decorarte Lucia Firmino", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/decorarte.luciafirmino/", 
             "address": "", "cover_image_url": ""},
            {"name": "Meduza Maria Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/meduzamaria/", 
             "address": "", "cover_image_url": ""},
            {"name": "Toque Fino Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/toque-finodecoracoes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Alfa Decorações", "category": "Decoração", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/decoradora_alfadecoracoes2/", 
             "address": "", "cover_image_url": ""},
            
            # --- Espaço ---
            {"name": "JS Recepções e Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98661-2686", "whatsapp": "+5583986612686", "instagram": "https://www.instagram.com/js.recepcoescg/",
             "address": "R. Maria Eva Moura, 342 - Cinza, Campina Grande - PB, 58423-490", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/js_recepcoes_placeholder.jpg"},
            {"name": "Quinta da Colina Maison", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 9 9972-2269", "whatsapp": "+558399722269", "instagram": "https://www.instagram.com/quintadacolinabuffet/",
             "address": "R. João Quirino, 1010 - Catolé, Campina Grande - PB, 58410-440", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/quinta_colina_placeholder.jpg"},
            {"name": "Encanto Verde Buffet e Recepções", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98710-8207", "whatsapp": "+5583987108207", "instagram": "https://www.instagram.com/encantoverderecepcoes/",
             "address": "R. Ascendino Nobre de Almeida, 145 - Cruzeiro, Campina Grande - PB, 58415-515", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/encanto_verde_placeholder.jpg"},
            {"name": "Espaço Lumë e Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99118-3388", "whatsapp": "+5583991183388", "instagram": "https://www.instagram.com/espacolume_/",
            "address": "R. Severino Pimentel, 462 - Liberdade, Campina Grande, 58414-150", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/espaco_lume_placeholder.jpg"},
            {"name": "Grand Château Recepções", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98638-9551", "whatsapp": "+5583986389551", "instagram": "https://www.instagram.com/grandchateaurecepcoes/",
            "address": "R. José Jesuíno de Brito, 100 - Jardim Quarenta, Campina Grande - PB, 58416-270", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/grand_chateau_placeholder.jpg"},
            {"name": "Fleur de Lys Recepções", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98638-9551", "whatsapp": "+5583986389551", "instagram": "https://www.instagram.com/fleurdelysrecepcoes/",
             "address": "R. da República, 1151 - Santa Rosa, Campina Grande - PB, 58416-576", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/fleur_de_lys_placeholder.jpg"},
            {"name": "Espaço Imbituba Buffet", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99955-3019", "whatsapp": "+5583999553019", "instagram": "https://www.instagram.com/espacoimbitubabuffet/",
             "address": "Av. Paris - Cuités, Campina Grande - PB, 58115-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/espaco_imbituba_placeholder.jpg"},
            {"name": "Di Fiori - Espaço de Eventos", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99308-9751", "whatsapp": "+5583993089751", "instagram": "https://www.instagram.com/difiori.eventos/",
             "address": "Av. Internacional, 52 - Nações, Campina Grande - PB, 58402-747", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/di_fiori_placeholder.jpg"},
            {"name": "Boucheree Recepções", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98801-9487", "whatsapp": "+5583988019487", "instagram": "https://www.instagram.com/bouchereebuffet/",
             "address": " R. Dr. João Moura, 245 - São José, Campina Grande - PB, 58400-344", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/boucheree_placeholder.jpg"},
            {"name": "DJu Festas & Eventos", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98889-6810", "whatsapp": "+5583988896810", "instagram": "https://www.instagram.com/djufestas/",
             "address": "R. Porto Velho, 32 - Três Irmãs, Campina Grande - PB, 58423-006", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/dju_festas_placeholder.jpg"},
            {"name": "Mastodonte Casa de Festas", "category": "Buffet", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 98166-4013", "whatsapp": "+5583981664013", "instagram": "https://www.instagram.com/mastodontectc/",
             "address": "Campina grande - BR-230, 3770 - Campina Grande, PB, 58443-000", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1778952063/mastodonte_placeholder.jpg"},
            {"name": "Navi Recepções", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/navirecepcoes/", 
             "address": "", "cover_image_url": ""},
            {"name": "La Paloma Recepções", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/lapalomarecepcoes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Cabanas Lago da Colina", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cabanaslagodacolina.oficial/", 
             "address": "", "cover_image_url": ""},
            {"name": "Espaço Ágape", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/espacoagape_cg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Monteville Privê", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/montevilleprive/", 
             "address": "", "cover_image_url": ""},
            {"name": "Solarium Casa de Eventos", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/solariumcasadeeventos/", 
             "address": "", "cover_image_url": ""},
            {"name": "Elaine Recepções", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/elainerecepcoes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Bubão Casa de Eventos", "category": "Espaço", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/bubaocasadeeventos/", 
             "address": "", "cover_image_url": ""},
            {"name": "Villas de Areia", "category": "Espaço", "city": "Areia", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/villasdeareiaoficial/", 
             "address": "", "cover_image_url": ""},


            # --- Convites ---
            {"name": "Papyrus Ateliê", "category": "Convites", "city": "Campina Grande", "state": "Paraíba", "phone": "(83) 99144-2769", "whatsapp": "+5583991442769", "instagram": "https://www.instagram.com/papyrusatelie/",
             "address": "R. Acre, 225 - Liberdade, Campina Grande - PB, 58414-260", "cover_image_url": "https://res.cloudinary.com/freelancerinc/image/upload/v1779104874/Design_sem_nome_1_zoy6vi.jpg"},
            {"name": "Sertec Copiadora e Gráfica", "category": "Convites", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/serteccopiadoraegrafic/", 
             "address": "", "cover_image_url": ""},
            {"name": "Top Bottons Papelaria", "category": "Convites", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/topbottons/", 
             "address": "", "cover_image_url": ""},
            {"name": "Papelário Artesanal", "category": "Convites", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/papelario_/", 
             "address": "", "cover_image_url": ""},

            # --- Bolo ---
            {"name": "Docinhos da Jir", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/docinhosdajir_cg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Clecius Rocha", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cleciusrocha/", 
             "address": "", "cover_image_url": ""},
            {"name": "Fresh Cake CG", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/freshcakecg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Adriana Pala Doce", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/adrianapaladoce/", 
             "address": "", "cover_image_url": ""},
            {"name": "Delícias da Ká", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/deliciasdaka_cardigna/", 
             "address": "", "cover_image_url": ""},
            {"name": "Maglize Confeitaria", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/maglize__/", 
             "address": "", "cover_image_url": ""},
            {"name": "Marta Brayner Bolos Fake", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/martabrayner/", 
             "address": "", "cover_image_url": ""},
            {"name": "Ded Festas", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/dedfestas_/", 
             "address": "", "cover_image_url": ""},
            {"name": "Naide Henriques Bolos e Doces", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/naidehenriquess/", 
             "address": "", "cover_image_url": ""},
            {"name": "Márcio Gourmet Bolos", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/marciogourmet/", 
             "address": "", "cover_image_url": ""},
            {"name": "Nelma Cardoso Confeitaria", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/nelmacardoso.silva/", 
             "address": "", "cover_image_url": ""},
            {"name": "Elsa Doce Arte", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/elsac_docearte/", 
             "address": "", "cover_image_url": ""},
            {"name": "Marques Cake Doceria", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/marquescakedoceria/", 
             "address": "", "cover_image_url": ""},
            {"name": "Divine Bolos e Doces", "category": "Bolo", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/divinebolosedoces/", 
             "address": "", "cover_image_url": ""},
            
            # --- Doces ---
            {"name": "Laah na Cozinha", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/laahnacozinha/", 
             "address": "", "cover_image_url": ""},
            {"name": "Miguelitos Brownies", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/miguelitosbrowniescg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Delícia na Chapa", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/delicianachapa_/", 
             "address": "", "cover_image_url": ""},
            {"name": "Chocomagic Doces", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/chocomagicdoc/", 
             "address": "", "cover_image_url": ""},
            {"name": "Caramella Brigaderia", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/caramellabrigaderia.cg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Maria Amendoa Doceria", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/mariaamendoadoceria/",
             "address": "", "cover_image_url": ""},
            {"name": "La Rose Doces", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/la.rosedoces/",
              "address": "", "cover_image_url": ""},
            {"name": "Dona Forminha PB", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/donaforminhapb/", 
             "address": "", "cover_image_url": ""},
            {"name": "Doceria 3 Irmãs", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/doceria3irmasbolosedoces/",
             "address": "", "cover_image_url": ""},
            {"name": "Bem Casados Docely", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/bemcasadosdocely/", 
             "address": "", "cover_image_url": ""},
            {"name": "Jake Doces e Cupcakes", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/jakedoces/", 
             "address": "", "cover_image_url": ""},
            {"name": "Doces Benevenuto", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/doces.benevenuto/",
              "address": "", "cover_image_url": ""},
            {"name": "Marriage Doces Finos", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/marriage_docesfinos/", 
             "address": "", "cover_image_url": ""},
            {"name": "Angelia Doces e Salgados", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/angeliadocesesalgados/",
              "address": "", "cover_image_url": ""},
            {"name": "La Doci Confeitaria", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/ladoci_confeitaria/", 
             "address": "", "cover_image_url": ""},
            {"name": "Poly Doces", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/polydoces_/", 
             "address": "", "cover_image_url": ""},
            {"name": "T Doces", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/tdoces__/", 
             "address": "", "cover_image_url": ""},
            {"name": "Edilene Egito Bem Vividos", "category": "Doces", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/edileneegito/", 
             "address": "", "cover_image_url": ""},
            
            # --- Vestido ---
            {"name": "Estilista Alberico Ribeiro", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/estilista.albericoribeiro/", 
             "address": "", "cover_image_url": ""},
            {"name": "Mariée Blanc", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/marieeblanc/", 
             "address": "", "cover_image_url": ""},
            {"name": "Atelier Vanúbia Fernandes", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/ateliervanubiafernandes/", 
             "address": "", "cover_image_url": ""},
            {"name": "Close Aluguel", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/close.aluguel/", 
             "address": "", "cover_image_url": ""},
            {"name": "Evidência Aluguel de Trajes", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/evidencia.aluguel/", 
             "address": "", "cover_image_url": ""},
            {"name": "Encantos de Clara Noivas", "category": "Vestido", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/encantosdeclara/", 
             "address": "", "cover_image_url": ""},
            
            # --- Lua de mel ---

            # --- Beleza da Noiva ---
            {"name": "Manu Buriti Beauty", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/manuburiti.beauty/", 
             "address": "", "cover_image_url": ""},
            {"name": "Clarissa e Micaella Beauty", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/clarissaemicaella/", 
             "address": "", "cover_image_url": ""},
            {"name": "Natielly Camilo Beauty", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/natiellycamilobeauty/", 
             "address": "", "cover_image_url": ""},
            {"name": "Lissandra Palmeira Beauty", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/lissandrapalmeiraa/", 
             "address": "", "cover_image_url": ""},
            {"name": "Samylla Soaress Makeup", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/samylla.soaressmakeup/", 
             "address": "", "cover_image_url": ""},
            {"name": "Studio Dalyanne Pereira", "category": "Beleza da Noiva", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/studiodalyannepereira/", 
             "address": "", "cover_image_url": ""},
            {"name": "Camarim SDB Beauty", "category": "Beleza", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/camarimsdb/", 
             "address": "", "cover_image_url": ""},
            {"name": "Aldenize Makeup", "category": "Beleza", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/aldenizemakeup/", 
             "address": "", "cover_image_url": ""},
            {"name": "Elen Lucena Studio de Beleza", "category": "Beleza", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/elenlucena_studiodebeleza/", 
             "address": "", "cover_image_url": ""},
            {"name": "Anna Almeida Makeup", "category": "Beleza", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/annalmeidamakeup/", 
             "address": "", "cover_image_url": ""},

            # --- Open Bar ---
            {"name": "Bar Service PB", "category": "Open Bar", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/barservicepb/", 
             "address": "", "cover_image_url": ""},
            {"name": "Marota Drinks e Coquetéis", "category": "Open Bar", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/marotadrinksecoqueteis/", 
             "address": "", "cover_image_url": ""},
            {"name": "Cocktail Show Drinks", "category": "Drinks", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/cocktailshowdrinks/", 
             "address": "", "cover_image_url": ""},

            # --- Outros ---
            {"name": "Telelê Store", "category": "Outros", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/telelestore/", 
             "address": "", "cover_image_url": ""},
            {"name": "Meus Mimos Artesanato", "category": "Outros", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/meusmimos_artesanato/", 
             "address": "", "cover_image_url": ""},
            {"name": "Innovere Chaveiros Promocionais", "category": "Outros", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/innovere.cg/", 
             "address": "", "cover_image_url": ""},
            {"name": "Oxe Concretos Suculentas", "category": "Outros", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/oxeconcretos/", 
             "address": "", "cover_image_url": ""},
            {"name": "Eternizar Foto Cabine", "category": "Fotografia", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/eternizarfotocabine/", 
             "address": "", "cover_image_url": ""},
            {"name": "Bella Letras 3D Iluminadas", "category": "Estrutura", "city": "Campina Grande", "state": "Paraíba", "phone": "", "whatsapp": "", "instagram": "https://www.instagram.com/bellaletras3d/", 
             "address": "Centro, Campina Grande - PB, 58100-000", "cover_image_url": ""},

        ]

        # 3. Inserir Fornecedores garantindo a não-duplicação
        created_count = 0
        for supplier_info in suppliers_data:
            category_obj = category_objects[supplier_info["category"]]
            
            # Usa name + category para checar a existência
            supplier, created = Supplier.objects.get_or_create(
                name=supplier_info["name"],
                category=category_obj,
                defaults={
                    "city": supplier_info["city"],
                    "state": "PB",
                    "status": Supplier.STATUS_APPROVED,  # Já cria aprovado por padrão
                    "description": f"Fornecedor de {supplier_info['category']} localizado em {supplier_info['city']} - PB.",
                    "phone": supplier_info.get("phone", ""),
                    "whatsapp": supplier_info.get("whatsapp", ""),
                    "instagram": supplier_info.get("instagram", ""),
                    "address": supplier_info.get("address", ""),
                    "cover_image_url": supplier_info.get("cover_image_url", ""),
                    "website": supplier_info.get("website", ""),
                }
            )
            
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Processo concluído! {created_count} novos fornecedores foram adicionados à base."
        ))